#pragma once


#define USE_SERIAL
#define MASTER_LEFT
// #define TAPPING_FORCE_HOLD
#define TAPPING_TERM 150
#define TAPPING_TERM_MODIFIER 150
#define TAPPING_TERM_LAYER 200
#define TAPPING_TERM_PER_KEY
#define SWAP_HANDS_ENABLE